spring.application.name=app
spring.datasource.url=jdbc:mysql://localhost:3306/smart_dorji_db
spring.datasource.username=root
spring.datasource.password=kalaboys12@VV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
